### ISSUE TITLE
Trackpad control 

### ISSUE THREAD

**Issue by cris691** [zlu883/Noodel#5]
I'm having trouble using a trackpad to reliably move from one node to the next.

The scroll from my mouse wheel works precisely to move by 1 node up or down, but trackpad scroll seems to overshoot.

I think there will be a way to fix this, but it could be tricky getting it to work across devices.

Tested on Chrome on Windows on a laptop.

**Comment by zlu883** [comment]
Currently scroll navigation works by moving 1 node per WheelEvent. I've not tested it with a trackpad, but I imagine it probably sends events at a rate that exceeds a comfortable threshold.

I think putting a debouncer on wheel events may do the trick. But it'll be great to have more data on this.

**Comment by cris691** [comment]
Sounds like a good fix, good luck.

**Comment by cris691** [comment]
Sounds like a good fix. I won't get more data for this, you're on you're own.
